-- MySQL Script generated by MySQL Workbench
-- Wed Oct 21 15:56:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE=`ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION`;

-- -----------------------------------------------------
-- Schema uni
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `universidad` ;

-- -----------------------------------------------------
-- Schema uni
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `universidad` DEFAULT CHARACTER SET utf8 ;
USE `universidad` ;

-- -----------------------------------------------------
-- Table `universidad`.`profesores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universidad`.`profesores` ;

CREATE TABLE IF NOT EXISTS `universidad`.`profesores` (
  `matricula` INT UNSIGNED NOT NULL,
  `dni` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `cuil` INT UNSIGNED NOT NULL,
  `genero` VARCHAR(45) NULL,
  PRIMARY KEY (`matricula`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universidad`.`alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universidad`.`alumnos` ;

CREATE TABLE IF NOT EXISTS `universidad`.`alumnos` (
  `LU` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dni` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  PRIMARY KEY (`LU`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  UNIQUE INDEX `LU_UNIQUE` (`LU` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universidad`.`datos_de_contacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universidad`.`datos_de_contacto` ;

CREATE TABLE IF NOT EXISTS `universidad`.`datos_de_contacto` (
  `dni_persona` INT UNSIGNED NOT NULL,
  `mail` VARCHAR(60) NOT NULL,
  `telefono` INT UNSIGNED NULL,
  `calle` VARCHAR(45) NULL,
  `numero` INT UNSIGNED NULL,
  `piso` VARCHAR(10) NULL,
  PRIMARY KEY (`dni_persona`),
  UNIQUE INDEX `dni_persona_UNIQUE` (`dni_persona` ASC) VISIBLE,
  CONSTRAINT `fk_datos_alumnos`
    FOREIGN KEY (`dni_persona`)
    REFERENCES `universidad`.`alumnos` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_datos_profe`
    FOREIGN KEY (`dni_persona`)
    REFERENCES `universidad`.`profesores` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universidad`.`carreras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universidad`.`carreras` ;

CREATE TABLE IF NOT EXISTS `universidad`.`carreras` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `duracion` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`nombre`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universidad`.`inscripciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universidad`.`inscripciones` ;

CREATE TABLE IF NOT EXISTS `universidad`.`inscripciones` (
  `fecha` DATE NOT NULL,
  `nombre_carrera` VARCHAR(45) NOT NULL,
  `LU_alumnos` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`nombre_carrera`, `LU_alumnos`, `fecha`),
  INDEX `LU_alumno_idx` (`LU_alumnos` ASC) VISIBLE,
  CONSTRAINT `fk_carrera_inscripciones`
    FOREIGN KEY (`nombre_carrera`)
    REFERENCES `universidad`.`carreras` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lu_inscripciones`
    FOREIGN KEY (`LU_alumnos`)
    REFERENCES `universidad`.`alumnos` (`LU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universidad`.`planes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universidad`.`planes` ;

CREATE TABLE IF NOT EXISTS `universidad`.`planes` (
  `nombre_carrera` VARCHAR(45) NOT NULL,
  `version` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`nombre_carrera`, `version`),
  CONSTRAINT `fk_planes`
    FOREIGN KEY (`nombre_carrera`)
    REFERENCES `universidad`.`carreras` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universidad`.`materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universidad`.`materias` ;

CREATE TABLE IF NOT EXISTS `universidad`.`materias` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `carga_horaria` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universidad`.`correlativas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universidad`.`correlativas` ;

CREATE TABLE IF NOT EXISTS `universidad`.`correlativas` (
  `id_materia` INT UNSIGNED NOT NULL,
  `id_correlativa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_materia`, `id_correlativa`),
  CONSTRAINT `fk_materia`
    FOREIGN KEY (`id_materia`)  REFERENCES `universidad`.`materias` (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
   CONSTRAINT `fk_correlativa`
    FOREIGN KEY (`id_correlativa`)  REFERENCES `universidad`.`materias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
 )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universidad`.`notas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universidad`.`notas` ;

CREATE TABLE IF NOT EXISTS `universidad`.`notas` (
  `LU_alumnos` INT UNSIGNED NOT NULL,
  `id_materia` INT UNSIGNED NOT NULL,
  `fecha_evaluacion` DATE NOT NULL,
  `puntaje` INT UNSIGNED NOT NULL,
  `estado` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`LU_alumnos`, `id_materia`, `fecha_evaluacion`),
  INDEX `id_materia_idx` (`id_materia` ASC) VISIBLE,
  CONSTRAINT `fk_lu_nota`
    FOREIGN KEY (`LU_alumnos`)
    REFERENCES `universidad`.`alumnos` (`LU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materia_nota`
    FOREIGN KEY (`id_materia`)
    REFERENCES `universidad`.`materias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universidad`.`dictan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universidad`.`dictan` ;

CREATE TABLE IF NOT EXISTS `universidad`.`dictan` (
  `id_materia` INT UNSIGNED NOT NULL,
  `matricula_profesor` INT UNSIGNED NOT NULL,
  `año` YEAR NOT NULL,
  `cuatrimestre` SMALLINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_materia`, `año`, `cuatrimestre`),
  INDEX `matricula_profesor_idx` (`matricula_profesor` ASC) VISIBLE,
  CONSTRAINT `fk_materia_dicta`
    FOREIGN KEY (`id_materia`)
    REFERENCES `universidad`.`materias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_dicta`
    FOREIGN KEY (`matricula_profesor`)
    REFERENCES `universidad`.`profesores` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE = ``;
DROP USER IF EXISTS admin_uni;
SET SQL_MODE=`ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION`;
CREATE USER admin_uni IDENTIFIED BY 'pwadmin';

GRANT SELECT, INSERT, TRIGGER ON TABLE `universidad`.* TO admin_uni;
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `universidad`.* TO admin_uni;
GRANT SELECT ON TABLE `universidad`.* TO admin_uni;
GRANT ALL ON `universidad`.* TO admin_uni;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
